//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : itool.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_IRAYSELECTEDTOOL_H)
#define _IRAYSELECTEDTOOL_H

#include "vrmine/vr_systemui/systemui_config.h"
#include "vrmine\vr_core\event.h"
#include "vrmine\vr_spatialinterface\itool.h"
#include "vrmine\vr_scenecontrol\geospatialcontrol.h"

namespace VirtualMine
{
	namespace SystemUI
	{
		class VR_SYSTEMUI_DLL CRaySelectedTool : public VirtualMine::SpatialInterface::CTool
		{
		public:
			CRaySelectedTool();
			virtual ~CRaySelectedTool();
			void mouseReleaseEvent(const int& x ,const int& y , const int& button);
			void mousePressEvent(const int& x ,const int& y , const int& button);
			void mouseDoubleClickEvent(const int& x ,const int& y , const int& button);
			void mouseMoveEvent(const int& x ,const int& y, const int& button);
			void wheelEvent(const int& x ,const int& y , const int& delta);
			void keyPressEvent(const int& key);
			bool handleEvent(VirtualMine::Core::CEvent* evt);
			void setGeoSpatialControl(VirtualMine::Scene::CGeoSpatialControl* ref_pGeoSpatialControl);

		protected:
			VirtualMine::Scene::CGeoSpatialControl* ref_mpGeoSpatialControl;
		};
	}
}

#endif  //_ITOOL_H
