//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : tunnelrenderableobject.h
//  @ Date : 2014/8/6
//  @ Author : 朱炜鹏
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_DRILLRENDERABLEOBJECT_H)
#define _DRILLRENDERABLEOBJECT_H


#include "vrmine/vr_spatialrender/baserender/geomultirenderableobject.h"
#include "vrmine/vr_arithmetic/arithmetic/drill_meshcreator.h"
#include <OGRE/Ogre.h>
namespace VirtualMine
{
	namespace SpatialRender
	{
		class VR_SPATIALRENDER_DLL CDrillRenderableObject : public VirtualMine::BaseRender::CGeoMultiRenderableObject
		{
		public:
			CDrillRenderableObject();
			~CDrillRenderableObject();	
		public:
			virtual void dispose();
			void build();
			void render();
			void deRender();
			void setMaterialName(const std::string& materialName);
		};
	}
}

#endif  //_DRILLRENDERABLEOBJECT_H
