//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : tunnelrenderableobject.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_TUNNELRENDERABLEOBJECT_H)
#define _TUNNELRENDERABLEOBJECT_H

#include "vrmine/vr_spatialrender/baserender/geomultirenderableobject.h"
#include "vrmine/vr_arithmetic/arithmetic/laneway_meshcreator.h"

namespace VirtualMine
{
	namespace SpatialRender
	{
		class VR_SPATIALRENDER_DLL CLanewayRenderableObject : public VirtualMine::BaseRender::CGeoMultiRenderableObject
		{
		public:
			CLanewayRenderableObject();
			~CLanewayRenderableObject();	
		public:
			void build();
			void render();
			void deRender();

		};
	}
}

#endif  //_TUNNELRENDERABLEOBJECT_H
