//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : geospatialcontrol.cpp
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#include "vrmine\vr_scenecontrol\scenequerylistener.h"


namespace VirtualMine
{
	namespace Scene
	{
		CSceneQueryListener::CSceneQueryListener()
		{
		
		}
		
		CSceneQueryListener::~CSceneQueryListener()
		{
		
		}

		void CSceneQueryListener::onRayQuery(Ogre::RaySceneQueryResultEntry& resultObject)
		{
		
		}
	}
}
