//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : CLanewayLayer.h
//  @ Date : 2014/7/27
//  @ Author : 盛佳良
//
//


#if !defined(_CDRILLLAYER_H)
#define _CDRILLLAYER_H

#include "vrmine/vr_spatiallayer/scenelayer.h"
#include "vrmine/vr_spatialinterface/igeoobject.h"

namespace VirtualMine
{
    namespace SpatialLayer
    {
        class VR_SPATIALLAYER_DLL CDrillLayer : public CSceneLayer
        {
        public:
			CDrillLayer();
			virtual ~CDrillLayer();
			virtual void update();
			virtual void initialise();
			virtual void notifyUpdate();
			virtual void getNearerGeoObjects(const Ogre::Vector3& referencePoint,
				const int& numOfNearerGeoObject,
				VirtualMine::SpatialInterface::GeoObjectMap& result);
			virtual void setFrameMode(bool isFrameMode);
        };
    }
}

#endif  //_CLanewayLayer_H
