//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : CLanewayLayer.h
//  @ Date : 2014/7/27
//  @ Author : 盛佳良
//
//


#if !defined(_CMININGAREALAYER_H)
#define _CMININGAREALAYER_H

#include "vrmine/vr_spatiallayer/scenelayer.h"

namespace VirtualMine
{
    namespace SpatialLayer
    {
        class VR_SPATIALLAYER_DLL CMiningAreaLayer : public CSceneLayer
        {
        public:
			CMiningAreaLayer();
			virtual ~CMiningAreaLayer();
			virtual void update();
			virtual void initialise();
			virtual void notifyUpdate();
        };
    }
}

#endif  //_CLanewayLayer_H
