//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : line.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_LINE_H)
#define _LINE_H

#include "vrmine/vr_spatialinterface/igeometry.h"
#include "vrmine/vr_core/coredefine.h"
#include "vrmine/vr_geometry/geometry/point.h"

namespace VirtualMine
{
	namespace Geometry
	{
		class VR_GEOMETRY_DLL CLine : public VirtualMine::SpatialInterface::CGeometry
		{
		public:
			CLine();
			virtual ~CLine();
			virtual void addPoint(CPoint& point);
			virtual void addPoint(const double& x,const double& y,const double& z);
			virtual CPoint getPoint(const size_t& index);
			virtual size_t getCount();
			virtual void removePoint(const size_t& index);
			virtual void removeAllPoints();
			virtual void toStream(VirtualMine::Core::CVRDataStream& datastream);
			virtual void fromStream(VirtualMine::Core::CVRDataStream& datastream);
			virtual void addPointID(int ID);
			virtual int getPointID(const size_t& index);
		private:
			DoubleVector mXCoors; 
			DoubleVector mYCoors;
			DoubleVector mZCoors;
			std::vector<int> IDvector;
		};
	}
}

#endif  //_LINE_H
