//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : miningarea.h
//  @ Date : 2014/8/6
//  @ Author : 朱炜鹏
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_MININGAREA_H)
#define _MININGAREA_H

#include "vrmine/vr_spatialinterface/igeometry.h"
#include "vrmine\vr_geometry\geometry\geometry_config.h"
#include "vrmine/vr_core/coredefine.h"
#include "vrmine/vr_geometry/geometry/polygon.h"
#include <OGRE/Ogre.h>

namespace VirtualMine
{
	namespace Geometry
	{
		class VR_GEOMETRY_DLL CMiningAreaGeometry : public VirtualMine::Geometry::CPolygon
		{
		public: 
			CMiningAreaGeometry();
			~CMiningAreaGeometry();
		};
	}
}

#endif  //_MININGAREA_H
