//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : coallayerdataset.h
//  @ Date : 2015/8/6
//  @ Author : 王凯
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 

#if !defined(_ESCAPEROUTEDATASET_H)
#define _ESCAPEROUTEDATASET_H


#include "vrmine/vr_databaseengine/database/dataset.h"
#include "bang/rocklayerconfig.h"


namespace VirtualMine
{
	namespace Bang_Database
	{
		class VR_BANG_DATABASEENGINE_DLL CEscapeRouteDataset : public VirtualMine::Database::CDataset
		{
		public:
			CEscapeRouteDataset();

			~CEscapeRouteDataset();

		};
	}
}

#endif //_ESCAPEROUTEDATASET_H
