//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : coallayerfeature.h
//  @ Date : 2015/7/30
//  @ Author : 王凯
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 



#if !defined(_PROJECTFEATURE_H)
#define _PROJECTFEATURE_H

#include "vrmine/vr_databaseengine/database/feature.h"
#include "vrmine/vr_databaseengine/database/field.h"
#include "bang/rocklayerconfig.h"
#include "vrmine/vr_databaseengine/database/propertyset.h"

namespace VirtualMine
{
	namespace Bang_Database
	{
		class VR_BANG_DATABASEENGINE_DLL CLanewaySectionFeature : public VirtualMine::Database::CFeature
		{
		public:
			CLanewaySectionFeature(); 

			~CLanewaySectionFeature();  

			std::string getName();

			void setName(const std::string& name);

			void addField(VirtualMine::Database::CField field);

			VirtualMine::Database::CField getValue(const int& index);

			VirtualMine::Database::CPropertySet* getPropertySet();

			void setFieldID(const int& id);
			int getFieldID();

			void setFieldName(const std::string& name);
			std::string getFieldName();

			void setFieldType(const std::string& type);
			std::string getFieldType();

			void setFieldParameter1(const float& parameter1);
			float getFieldParameter1();       
			void setFieldParameter2(const float& parameter2);
			float getFieldParameter2(); 
			void setFieldParameter3(const float& parameter3);
			float getFieldParameter3(); 
			void setFieldParameter4(const float& parameter4);
			float getFieldParameter4(); 
			void setFieldParameter5(const float& parameter5);
			float getFieldParameter5(); 


		/*	void setFieldHeight(const float& height);
			float getFieldHeight();
			void setFieldWidth(const float& width);
			float getFieldWidth();

			void setFieldRadius(const float& radius);
			float getFieldRadius();*/

		};
	}
}

#endif //_PROJECTFEATURE_H