//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : cardmodelproperty.h
//  @ Date : 2014/8/6
//  @ Author : 朱炜鹏
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_CARDMODELPROPERTY_H)
#define _CARDMODELPROPERTY_H

#include "vrmine/vr_core/coredefine.h"
#include "vrmine/vr_spatialinterface/igeoproperty.h"
#include "vrmine\vr_spatialobject\spatialobject_config.h"
#include "vrmine\vr_core\geodatatype.h"
#include "vrmine\vr_core\variant.h"
#include "vrmine\vr_spatialobject\geoproperty\modelProperty.h"
namespace VirtualMine
{
	namespace GeoProperty
	{
		class VR_SPATIALOBJECT_DLL CCardModelProperty : public VirtualMine::GeoProperty::CModelProperty
		{
		public:
			CCardModelProperty();
			~CCardModelProperty();
		public:
			VirtualMine::SpatialInterface::IGeoProperty* clone();

			void setName(const std::string& name);
			std::string getName();

			void setStationID(const std::string& stationID);
			std::string getStationID();

			void setCardID(const std::string& cardID);
			std::string getCardID();

			void setDeviceKind(VirtualMine::Core::DeviceKind devicekind = VirtualMine::Core::DeviceKind::DK_UNKNOWN);
			VirtualMine::Core::DeviceKind getDeviceKind();

			/*void setMeshName(const std::string& meshName);
			std::string getMeshName();*/

			void toStream(VirtualMine::Core::CVRDataStream& datastream);
			void fromStream(VirtualMine::Core::CVRDataStream& datastream);
		private:
			std::string mName;
			std::string	mStationID;
			std::string mCardID;
			VirtualMine::Core::DeviceKind mDeviceKind;
		};
	}
}

#endif  //_CARDMODELPROPERTY_H
