//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : demobject.h
//  @ Date : 2014/8/6
//  @ Author : 朱炜鹏
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_DRILLPROPERTY_H)
#define _DRILLPROPERTY_H

#include "vrmine/vr_core/coredefine.h"
#include "vrmine/vr_spatialinterface/igeoproperty.h"
#include "vrmine\vr_spatialobject\spatialobject_config.h"
#include "vrmine\vr_core\variant.h"

namespace VirtualMine
{
	namespace GeoProperty
	{
		class VR_SPATIALOBJECT_DLL CStratum
		{
		public:
			CStratum();
			~CStratum();
		public:
			void setDepth(const float& depth);
			float getDepth();

			void setDescription(const std::string& description);
			std::string getDeccription();

			void setAge(const std::string& age);
			std::string getAge();

			void setFeatureInfo(const std::string& featureinfo);
			std::string getFeatureInfo();

			void toStream(VirtualMine::Core::CVRDataStream& datastream);

			void fromStream(VirtualMine::Core::CVRDataStream& datastream);
		private:
			float mDepth;
			std::string mDescription;
			std::string mAge;
			std::string mFeatureInfo;
		};

		class VR_SPATIALOBJECT_DLL CDrillProperty : public VirtualMine::SpatialInterface::CGeoProperty
		{
		public:
			CDrillProperty();
			~CDrillProperty();

		public:
			VirtualMine::SpatialInterface::IGeoProperty* clone();

			void setName(const std::string& name);
			std::string getName();

			void setRadius(float radius);
			float getRadius();

			void addStratum(VirtualMine::GeoProperty::CStratum* stratum);
			VirtualMine::GeoProperty::CStratum* getStratum(const int& index);
			int getStratumCount();
            
            void toStream(VirtualMine::Core::CVRDataStream& datastream);

			void fromStream(VirtualMine::Core::CVRDataStream& datastream);

			std::string toString();

		private:
			std::string mName;
			float mRadius;
			std::vector<VirtualMine::GeoProperty::CStratum*> mStratum; //  岩层
		};
	}
}

#endif  //_DRILLPROPERTY_H
