//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : mineproperty.h
//  @ Date : 2014/8/6
//  @ Author : 朱炜鹏
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_MINETPROPERTY_H)
#define _MINETPROPERTY_H

#include "vrmine/vr_core/coredefine.h"
#include "vrmine/vr_spatialinterface/igeoproperty.h"
#include "vrmine\vr_spatialobject\spatialobject_config.h"


namespace VirtualMine
{
	namespace GeoProperty
	{
		class VR_SPATIALOBJECT_DLL CMineProperty : public VirtualMine::SpatialInterface::CGeoProperty
		{
		public:
			CMineProperty();
			~CMineProperty();
		public:
			VirtualMine::SpatialInterface::IGeoProperty* clone();

			void setName(const std::string& name);
			std::string getName();

			void setDipAngle(const float& angle);
			float getDipAngle();

			void setHeight(const float& height);
			float getHeight();

			void setRadius(const float& radius);
			float getRadius();
		private:
			std::string mName;
			float mDipAngle;  //  倾角
			float mHeight;
			float mRadius;
		};
	}
}

#endif  //_MINETPROPERTY_H
