//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : miningareaproperty.h
//  @ Date : 2014/8/6
//  @ Author : 朱炜鹏
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_MININGAREAPROPERTY_H)
#define _MININGAREAPROPERTY_H

#include "vrmine/vr_core/coredefine.h"
#include "vrmine/vr_spatialinterface/igeoproperty.h"
#include "vrmine\vr_spatialobject\spatialobject_config.h"


namespace VirtualMine
{
	namespace GeoProperty
	{
		class VR_SPATIALOBJECT_DLL CMiningAreaProperty :public VirtualMine::SpatialInterface::CGeoProperty
		{
		public:
			CMiningAreaProperty();
			~CMiningAreaProperty();
		public:
			VirtualMine::SpatialInterface::IGeoProperty* clone();
			void setName(const std::string& name);
			std::string getName();

			void setCoalName(const std::string& name);
			std::string getCoalName();
		private:
			std::string mName;
			std::string mCoalName;
		};
	}
}

#endif  //_MININGAREAPROPERTY_H
