//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 二三维爆破信息仿真系统
//  @ File Name : cellipsedrawitem.h
//  @ Date : 2015/8/1
//  @ Author : 
//
//




#if !defined(_CELLIPSEDRAWITEM_H)
#define _CELLIPSEDRAWITEM_H

#include "igeometrydrawitem.h"

namespace VirtualMine
{
	namespace Map
	{
		class VR_MAPLAYER_EXPORT CEllipseDrawItem : public IGeometryDrawItem {
		};
	}}
#endif  //_CELLIPSEDRAWITEM_H
