//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 二三维爆破信息仿真系统
//  @ File Name : cellipse.h
//  @ Date : 2015/8/1
//  @ Author : 
//
//



#if !defined(_CELLIPSE_H)
#define _CELLIPSE_H

namespace VirtualMine
{
	namespace Map
	{

		class CEllipse /*: public IGeometry */
		{
		public:
			void setCenter();
			void getCenter();
			void setMajorSemiAxis();
			void getMajorSemiAxis();
			void setMinorSemiAxis();
			void getMinorSemiAxis();
		};
	}}
#endif  //_CELLIPSE_H
