//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : line.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_LINE2D_H)
#define _LINE2D_H

#include "vrmine/vr_spatialinterface/igeometry.h"
#include "vrmine/vr_core/coredefine.h"
#include "vrmine/vr_maplayer/point2D.h"
#include "vrmine/vr_maplayer/igeometrydrawitem.h"
#include "vrmine/vr_geometry/geometry/line.h"
namespace VirtualMine
{
	namespace Map
	{
		class VR_MAPLAYER_EXPORT CLine2D : public VirtualMine::Geometry::CLine
	{
		public:
			CLine2D();
			virtual ~CLine2D();
			
			virtual void setLineName(std::string& name);
			virtual std::string getName();
			virtual void addPointID(int ID);
			virtual int getPointID(const size_t& index);
			void setType(const int& type);//0表示三视图，1表示起爆顺序
			int getType();
	private:
		    int mType;		
			std::vector<int> mIDvector;
			std::string mName;
		};
	}
}

#endif  //_LINE_H


