//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 二三维爆破信息仿真系统
//  @ File Name : cpointlayer.h
//  @ Date : 2015/8/1
//  @ Author : 
//
//



#if !defined(_CPOINTLAYER_H)
#define _CPOINTLAYER_H

#include "map2dlayer.h"

namespace VirtualMine
{
	namespace Map
	{
		class CPointLayer : public CMap2DLayer {

		public:
			CPointLayer();
			virtual ~CPointLayer();
		};
	}}
#endif  //_CPOINTLAYER_H
