//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 二三维爆破信息仿真系统
//  @ File Name : cpolygondrawitem.h
//  @ Date : 2015/8/1
//  @ Author : 
//
//



#if !defined(_CPOLYGONDRAWITEM_H)
#define _CPOLYGONDRAWITEM_H

#include "igeometrydrawitem.h"

namespace VirtualMine
{
	namespace Map
	{
		class CPolygonDrawItem : public IGeometryDrawItem {
		};
	}}
#endif  //_CPOLYGONDRAWITEM_H
