//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 二三维爆破信息仿真系统
//  @ File Name : crectangle.h
//  @ Date : 2015/8/1
//  @ Author : 
//
//



#if !defined(_CRECTANGLE_H)
#define _CRECTANGLE_H

namespace VirtualMine
{
	namespace Map
	{

		class CRectangle /*: public IGeometry */
		{
		public:
			void setCenter();
			void getCenter();
			void setWidth();
			void getWidth();
			void setHeight();
			void getHeight();
		};
	}}
#endif  //_CRECTANGLE_H
