//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 二三维爆破信息仿真系统
//  @ File Name : cshapeitem.h
//  @ Date : 2015/8/1
//  @ Author : 
//
//



#if !defined(_CSHAPEITEM_H)
#define _CSHAPEITEM_H

#include "igeometrydrawitem.h"

namespace VirtualMine
{
	namespace Map
	{
		class VR_MAPLAYER_EXPORT CShapeItem : public IGeometryDrawItem ,public ISelectObject,public CVisibleObject
		{
		public:
			CShapeItem();
			virtual ~CShapeItem();
			virtual std::string getName();
			virtual void setName(const std::string& name);
			virtual VirtualMine::SpatialInterface::IGeometry* getGeometry();
			virtual VirtualMine::SpatialInterface::IStyle* getStyle();
			virtual void setBoundingBox(const Ogre::AxisAlignedBox& boundingBox);
			virtual Ogre::AxisAlignedBox& getBoundingBox();
			virtual bool pointSelect(const QPointF& mousePrjPos,const double& tolerance);
		protected:
			std::string mName;
			VirtualMine::SpatialInterface::IGeometry* mpGeometry;
			VirtualMine::SpatialInterface::IStyle* mpStyle;
			Ogre::AxisAlignedBox mBoundingBox;
		};
	}}
#endif  //_CSHAPEITEM_H
