//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 二三维爆破信息仿真系统
//  @ File Name : cpointdrawitem.h
//  @ Date : 2015/8/1
//  @ Author : 
//
//

#if !defined(_CTEXTDRAWITEMM_H)
#define _CTEXTDRAWITEMM_H

#include "igeometrydrawitem.h"
#include "vrmine/vr_maplayer/shapeitem.h"

namespace VirtualMine
{
	namespace Map
	{
		class VR_MAPLAYER_EXPORT CTextDrawItem : public CShapeItem {

		public:
			CTextDrawItem();
			virtual ~CTextDrawItem();
			virtual bool draw(QPainter& painter,
				const int& viewWidth,const int& viewHeight,
				const QPointF& viewLeftTopPosition,
				const QPointF& viewRightBottomPosition,
				const float& curScale);
		    void setType(const int& type);
			int getType();
		private:
			int mtype;
		};
	}}
#endif  //_CPOINTDRAWITEM_H
