//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : cylinder.cpp
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#include "vrmine\vr_geometry\geometry\cylinder.h"

namespace VirtualMine
{
	namespace Geometry
	{
		void CCylinder::getRadius()
		{

		}

		void CCylinder::setRadius()
		{

		}

		void CCylinder::getTop()
		{

		}

		void CCylinder::setTop()
		{

		}

		void CCylinder::getBottom()
		{

		}

		void CCylinder::setBottom()
		{

		}

	}
}
