//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : fault.cpp
//  @ Date : 2014/8/6
//  @ Author : 朱炜鹏
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#include "vrmine\vr_geometry\geometry\fault.h"

namespace VirtualMine
{
	namespace Geometry
	{
		CFaultGeometry::CFaultGeometry()
		{

		}
		CFaultGeometry::~CFaultGeometry()
		{

		}
	}
}
