//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : line.cpp
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#include "vrmine\vr_geometry\geometry\line.h"
#include "vrmine\vr_spatialinterface\iscene.h"

using namespace VirtualMine::SpatialInterface;

namespace VirtualMine
{
	namespace Geometry
	{

		CLine::CLine()
		{
		
		}
		
		CLine::~CLine()
		{
		
		}

		void CLine::addPoint(CPoint& point)
		{
			this->mXCoors.push_back(point.getX());
			this->mYCoors.push_back(point.getY());
			this->mZCoors.push_back(point.getZ());
		}

		void CLine::addPoint(const double& x,const double& y,const double& z)
		{
			this->mXCoors.push_back(x);
			this->mYCoors.push_back(y);
			this->mZCoors.push_back(z);
		}

		size_t CLine::getCount()
		{
			return this->mXCoors.size();
		}
		
		CPoint CLine::getPoint(const size_t& index)
		{
			assert(index < this->mXCoors.size());
			CPoint p;
			p.setX(this->mXCoors[index]);
			p.setY(this->mYCoors[index]);
			p.setZ(this->mZCoors[index]);
			return p;
		}
		
		void CLine::removeAllPoints()
		{
			this->mXCoors.clear();
			this->mYCoors.clear();
			this->mZCoors.clear();
		}

		void CLine::removePoint(const size_t& index)
		{
			assert(index < this->mXCoors.size());
			this->mXCoors.erase(this->mXCoors.begin() + index);
			this->mYCoors.erase(this->mYCoors.begin() + index);
			this->mZCoors.erase(this->mZCoors.begin() + index);
		}

		void CLine::toStream(VirtualMine::Core::CVRDataStream& datastream)
		{

			datastream.wirteInt32(mXCoors.size());
			for (int i = 0; i < mXCoors.size(); i++)
			{
				datastream.wirteReal(mXCoors[i]);
			}
		    for (int i = 0; i < mYCoors.size(); i++)
			{
				datastream.wirteReal(mYCoors[i]);
			}
			for (int i = 0; i < mZCoors.size(); i++)
			{
				datastream.wirteReal(mZCoors[i]);
			}

		}
		void CLine::fromStream(VirtualMine::Core::CVRDataStream& datastream)
		{
		

			int length(0);
			datastream.readInt32(length);
			double x,y,z;
			for (int i = 0; i < length; i++)
			{
				datastream.readReal(x);
				x = x - IScene::ReferenceCenter.x; 
				mXCoors.push_back(x);
			}
			for (int i = 0; i < length; i++)
			{
				datastream.readReal(y);
				y -= IScene::ReferenceCenter.y;
				mYCoors.push_back(y);

			}
			for (int i = 0; i < length; i++)
			{
				datastream.readReal(z);
				z = z - IScene::ReferenceCenter.z;
				//z *= IScene::CoefficientOfCoordinateTransform;
				mZCoors.push_back(z);
			}
		}

		void CLine::addPointID( int ID )
		{
			this->IDvector.push_back(ID);
		}

		int CLine::getPointID( const size_t& index )
		{
				assert(index < this->IDvector.size());
				int p;
				p=this->IDvector.at(index);
				return p;
		}

	}
}

