//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : workingplane.cpp
//  @ Date : 2014/10/26
//  @ Author : 王凯
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#include "vrmine\vr_geometry\geometry\workingplane.h"

namespace VirtualMine
{
	namespace Geometry
	{
		CWorkingplaneGeometry::CWorkingplaneGeometry()
		{

		}
		CWorkingplaneGeometry::~CWorkingplaneGeometry()
		{

		}
	/*	 void CWorkingplaneGeometry::toStream(VirtualMine::Core::CVRDataStream datastream)
		 {
			 CPolygon::toStream(datastream);
		 }*/

	/*	
		void CWorkingplaneGeometry::fromStream(VirtualMine::Core::CVRDataStream datastream)
		{
			CPolygon::fromStream(datastream);
		}*/


	}
}
