//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : fault_meshcreator.h
//  @ Date : 2014/7/5
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_CFAULT_MESHCREATOR_H)
#define _CFAULT_MESHCREATOR_H

#include "vrmine/vr_spatialinterface/igeomeshcreator.h"
#include "vrmine\vr_arithmetic\arithmetic_config.h"
#include <OGRE\Ogre.h>


namespace VirtualMine
{
	namespace Arithmetic
	{
		class VR_ARITHMETIC_DLL CFault_MeshCreator : public VirtualMine::SpatialInterface::CGeoMeshCreator
		{
		public:
			CFault_MeshCreator();
			~CFault_MeshCreator();
		public:
			void createData(VirtualMine::SpatialInterface::GeoObjectVector& geoObjectVector,std::vector<VirtualMine::SpatialInterface::CGeoExtentionData*>& geoExtentionDatas);

		};
	}
}

#endif  //_CFAULT_MESHCREATOR_H
