//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : cgeometryarithmeticlibrary.h
//  @ Date : 2014/7/5
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_CGEOMETRYARITHMETICLIBRARY_H)
#define _CGEOMETRYARITHMETICLIBRARY_H

#include "vrmine/vr_arithmetic/arithmetic_config.h"
#include "vrmine/vr_core/coredefine.h"

namespace VirtualMine
{
	namespace Arithmetic
	{
		class VR_ARITHMETIC_DLL CGeometryArithmeticLibrary
		{
		public:
			void createLineBufferArea();
			static void createTINData(CoorVector& vertexes,IntVector& indexes);
			void triangulatePolygon(CoorVector& vertexes,IntVector& indexes);
			void smoothingMeshData();
		};
	}
}

#endif  //_CGEOMETRYARITHMETICLIBRARY_H
