//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : cgeopolygon_meshcreator.h
//  @ Date : 2014/7/5
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_CGEOPOLYGON_MESHCREATOR_H)
#define _CGEOPOLYGON_MESHCREATOR_H

#include "igeomeshcreator.h"

namespace VirtualMine
{
	namespace Arithmetic
	{
		class VR_ARITHMETIC_DLL CGeoPolygon_MeshCreator : public IGeoMeshCreator
		{
		};
	}
}

#endif  //_CGEOPOLYGON_MESHCREATOR_H
