//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : geofactoryregister.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_GEOFACTORYREGISTER_H)
#define _GEOFACTORYREGISTER_H

#include "..\spatialobject_config.h"

namespace VirtualMine
{
	namespace GeoFactory
	{
		class VR_SPATIALOBJECT_DLL CGeoFactoryRegister
		{
		public:
			void registerGeoFactory();
			void unRegisterGeoFactory();
			void getGeoFactory();
			void getSingleton();
			void getSingletonPtr();
		};
	}
}

#endif  //_GEOFACTORYREGISTER_H
