//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : minefactory.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_MINEFACTORY_H)
#define _MINEFACTORY_H

#include "igeofactory.h"


namespace VirtualMine
{
	namespace GeoFactory
	{
		class VR_SPATIALOBJECT_DLL CMineFactory : public VirtualMine::GeoFactory::IGeoFactory
		{
		};
	}
}

#endif  //_MINEFACTORY_H
