//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : faultstyle.cpp
//  @ Date : 2014/8/6
//  @ Author : 朱炜鹏
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#include "vrmine\vr_style\style\faultstyle.h"

namespace VirtualMine
{
	namespace Style
	{
		CFaultStyle::CFaultStyle()
		{
			this->setTextureName("fault.png");

		}

		CFaultStyle::~CFaultStyle()
		{

		}

		void CFaultStyle::setFaultColor(const Ogre::ColourValue& color)
		{
			this->mColor = color;
		}

		Ogre::ColourValue CFaultStyle::getFaultColor()
		{
			return this->mColor;
		}

		void CFaultStyle::setTextureName(const std::string& name)
		{
			this->mTextureName = name;
		}

		std::string CFaultStyle::getTextureName()
		{
			return this->mTextureName;
		}
	}
}
