//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : surfacestyle.cpp
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#include "vrmine\vr_style\style\surfacestyle.h"

namespace VirtualMine
{
	namespace Style
	{
		void CSurfaceStyle::hasFrame()
		{

		}

		void CSurfaceStyle::setFrame()
		{

		}

	}
}
