//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : docktype.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_DOCKTYPE_H)
#define _DOCKTYPE_H


namespace VR_Style
{
    namespace VirtualMine
    {
        namespace Style
        {
            enum DockType
            {
                DS_Up,
                DS_Down,
                DS_Left,
                DS_Right
            };
        }
    }
}

#endif  //_DOCKTYPE_H
