//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : linestyle.h
//  @ Date : 2014/8/6
//  @ Author : 朱炜鹏
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_DRILLHOLESTYLE_H)
#define _DRILLHOLESTYLE_H

#include "vrmine\vr_style\style_config.h"
#include "vrmine/vr_spatialinterface/istyle.h"

namespace VirtualMine
{
	namespace Style
	{
		class VR_STYLE_DLL CDrillHoleStyle : public VirtualMine::SpatialInterface::CStyle
		{
		public:
			CDrillHoleStyle();
			~CDrillHoleStyle();
		public:
			void registStyle();

			void insertStratum(std::string stratumName,std::string textureName );
			std::string getMaterialName(std::string stratumName);

		private:
			std::map<std::string,std::string> mMapStratums;
		};
	}
}

#endif  //_DRILLHOLESTYLE_H
