//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : modelstyle.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_MODELSTYLE_H)
#define _MODELSTYLE_H

#include "vrmine\vr_style\style_config.h"
#include "vrmine/vr_spatialinterface/istyle.h"
#include "vrmine/vr_spatialinterface/parameter.h"

namespace VirtualMine
{
	namespace Style
	{
		class VR_STYLE_DLL CModelStyle : public VirtualMine::SpatialInterface::CStyle
		{
		public:
			CModelStyle();
			virtual ~CModelStyle();
			void setParameter(const VirtualMine::SpatialInterface::CParameter& parameter);
			VirtualMine::SpatialInterface::CParameter& getParameter();

		protected:
			VirtualMine::SpatialInterface::CParameter mParameter;
		};
	}
}

#endif  //_MODELSTYLE_H
