//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : pointstyle.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_POINTSTYLE_H)
#define _POINTSTYLE_H

#include "vrmine\vr_style\style_config.h"
#include "vrmine/vr_spatialinterface/istyle.h"

namespace VirtualMine
{
	namespace Style
	{
		class  VR_STYLE_DLL CPointStyle : public VirtualMine::SpatialInterface::CStyle
		{
		public:
			enum PointRenderMode
			{
				//颜色
				PRM_COLOUR,
				//图标
				PRM_ICON
			};
		public:
			CPointStyle();
			virtual ~CPointStyle();
			void setSize(const int& size);
			int getSize();
			void setIconName(const std::string& iconName);
			std::string getIconName();
			void setPointRenderMode(const PointRenderMode& renderMode);
			PointRenderMode getPointRenderMode();

		protected:
			int mSize;
			std::string mIconName;
			PointRenderMode mRenderMode;
		};
	}
}

#endif  //_POINTSTYLE_H
