//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : coordinatecalculator.cpp
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#include "vrmine\vr_coordinatesystem\coordinatesystem\spatialreference_beijing54.h"
#include "vrmine\vr_coordinatesystem\coordinatesystem\spatialreference_wgs84.h"
#include "vrmine\vr_coordinatesystem\coordinatesystem\spatialreference_xian80.h"

using namespace VirtualMine::SpatialInterface;

namespace VirtualMine
{
	namespace CoordinateSystem
	{
		CSpatialReference_WGS84::CSpatialReference_WGS84()
		{
			_a = 6378137.0;
			_f = 1.0 / 298.257223563;
			_spheroid = WGS84;
		}

		CSpatialReference_WGS84::~CSpatialReference_WGS84()
		{

		}

		CSpatialReference_BeiJing54::CSpatialReference_BeiJing54()
		{
			_a = 6378245.0;
			_f = 1.0 / 298.3;
			_spheroid = Beijing54;
		}

		CSpatialReference_BeiJing54::~CSpatialReference_BeiJing54()
		{

		}

		CSpatialReference_XiAn80::CSpatialReference_XiAn80()
		{
			_a = 6378140.0;
			_f = 1.0 / 298.257;
			_spheroid = Xian80;
		}

		CSpatialReference_XiAn80::~CSpatialReference_XiAn80()
		{

		}
	}
}
