//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : igeomeshcreator.h
//  @ Date : 2014/7/5
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_IGEOMESHCREATOR_H)
#define _IGEOMESHCREATOR_H

#include "vrmine\vr_spatialinterface\igeoobject.h"
#include <OGRE\Ogre.h>

namespace VirtualMine
{
	namespace SpatialInterface
	{
		class VR_SPATIALINTERFACE_DLL IGeoMeshCreator 
		{
		public:
			IGeoMeshCreator();
			virtual ~IGeoMeshCreator();
			virtual  void createData(GeoObjectVector& geoObjectVector,std::vector<VirtualMine::SpatialInterface::CGeoExtentionData*>& geoExtentionDatas) = 0;
			virtual std::string& getType() = 0;
			virtual void setType(std::string& type) = 0;
			virtual void setSceneMgr(Ogre::SceneManager* sceneMgr) = 0;
		    virtual std::vector<CGeoExtentionData*>* getGeoExtantionDataVector() = 0;
		};

		class VR_SPATIALINTERFACE_DLL CGeoMeshCreator :public IGeoMeshCreator
		{
		public:
			CGeoMeshCreator();
			virtual ~CGeoMeshCreator();
			void createData(GeoObjectVector& geoObjectVector,std::vector<VirtualMine::SpatialInterface::CGeoExtentionData*>& geoExtentionDatas);
			std::string& getType();
			void setType(std::string& type);
			void setSceneMgr(Ogre::SceneManager* sceneMgr);
			virtual std::vector<CGeoExtentionData*>* getGeoExtantionDataVector();
		protected:
			Ogre::SceneManager* ref_mpSceneMgr;
			std::string mType;
			GeoObjectVector ref_mGeoObjectVector;
			std::vector<CGeoExtentionData*>* ref_mGeoExtantionDataVector;
			//kk
			int mauobjectnum;
		};
	}
}

#endif  //_IGEOMESHCREATOR_H
