//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : irenderableobject.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_IRENDERABLEOBJECT_H)
#define _IRENDERABLEOBJECT_H

#include "vrmine\vr_spatialinterface\spatialinterface_config.h"
#include "vrmine\vr_core\baseobject.h"
#include "OGRE\OgreNode.h"
#include "OGRE/OgreSceneManager.h"
#include <string>

namespace VirtualMine
{
	namespace SpatialInterface
	{
		class VR_SPATIALINTERFACE_DLL IRenderableObject : public VirtualMine::Core::CBaseObject
		{
		public:
			IRenderableObject();
			virtual ~IRenderableObject();
			virtual void build();
			virtual void render();
			virtual void deRender();
			virtual void dispose();
			virtual Ogre::String getName();
			virtual void setName(const Ogre::String& name);
			virtual Ogre::Node* getNode();
			virtual void setNode(Ogre::Node* node);
			virtual void attachToNode(Ogre::Node* pNode);
			virtual void setGeoSceneManager(Ogre::SceneManager* ref_pGeoSceneManager);
			virtual Ogre::SceneManager* getGeoSceneManager();
		protected:
			Ogre::String mName;
			Ogre::Node* mpNode;
			Ogre::SceneManager* ref_mpGeoSceneManager;
			bool mHasRenderToScene;
		};
	}
}

#endif  //_IRENDERABLEOBJECT_H
