//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : itool.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#ifndef _VR_SPATIALINTERFACE
#define _VR_SPATIALINTERFACE

#ifndef VR_SPATIALINTERFACE_EXPORTS
#define VR_SPATIALINTERFACE_DLL _declspec(dllimport)
#else
#define VR_SPATIALINTERFACE_DLL _declspec(dllexport)
#endif

#endif  //_ITOOL_H
