//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : distancemeasuretool.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_DISTANCEMEASURETOOL_H)
#define _DISTANCEMEASURETOOL_H

#include "vrmine/vr_spatialanalyse/spatialanalyse/spatialmeasuretool.h"
#include "vrmine/vr_spatialrender/baserender/multiline.h"
#include "vrmine/vr_spatialrender/baserender/multipoint.h"
namespace VirtualMine
{
	namespace SpatialAnalyse
	{
		class VR_SPATIALANALYSE_DLL CDistanceMeasureTool : public CSpatialMeasureTool
		{
		public:
			CDistanceMeasureTool(VirtualMine::Scene::CGeoSpatialControl* ref_pSceneControl);
			virtual ~CDistanceMeasureTool();
			virtual void mouseReleaseEvent(const int& x ,const int& y , const int& button);
			virtual void mousePressEvent(const int& x ,const int& y , const int& button);
			virtual void mouseDoubleClickEvent(const int& x ,const int& y , const int& button);
			virtual void mouseMoveEvent(const int& x ,const int& y, const int& button);

			float getTieDiDistance();

			float getZhiXianDistance();

			void clear();		
		private:
			void interpolationPoints(CoorVector& points);
			void renderMoveLine();
		    void renderLine();		
		    void renderPoints();

			void removeMoveLineObject();
			void removeLineObject();
			void removePointsObject();
		private:
			CoorVector mMovePoints;
			CoorVector mMarkPoints;
			VirtualMine::BaseRender::CMultiLine* mpRenderLine;
			VirtualMine::BaseRender::CMultiLine* mpRenderMoveLine;
			VirtualMine::BaseRender::CMultiPoint* mpRenderPoints;
			float mInterpolationValue;

			float mTieDiDistance;
			float mZhiXianDistance;
		};
	}
}
#endif  //_DISTANCEMEASURETOOL_H
