//#include "stdafx.h"
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : Delaunay.h
//  @ Date : 2015/6/18
//  @ Author : 王向上
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 

#if !defined(_ISO_CONTOUR_H)
#define _ISO_CONTOUR_H

#include "vrmine/vr_spatialanalyse/spatialanalyse_config.h"
#include "vrmine/vr_core/coredefine.h"
#include <iostream>
#include <cmath>
#include <vector>

namespace VirtualMine
{
	namespace SpatialAnalyse
	{

		class  VR_SPATIALANALYSE_DLL iso_contour
		{
		public:
			iso_contour();
			~iso_contour();

		public:
			std::vector<De_point> isoline_con(std::vector<De_point>& V,double h);

		private:
			std::vector<De_point> V;
			int h;
		    De_point first_1,second_2;
		 
			
		private:
			

		};
	}
}

#endif  //_DISTANCEMEASURETOOL_H