//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : pointmeasuretool.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_POINTMEASURETOOL_H)
#define _POINTMEASURETOOL_H

#include "vrmine/vr_spatialanalyse/spatialanalyse/spatialmeasuretool.h"
#include "vrmine/vr_spatialrender/baserender/multipoint.h"

namespace VirtualMine
{
	namespace SpatialAnalyse
	{
		class VR_SPATIALANALYSE_DLL CPointMeasureTool : public CSpatialMeasureTool
		{
		public:
			CPointMeasureTool(VirtualMine::Scene::CGeoSpatialControl* ref_pSceneControl);
			virtual ~CPointMeasureTool();
			virtual void mouseReleaseEvent(const int& x ,const int& y , const int& button);
			virtual bool handleEvent(VirtualMine::Core::CEvent* evt);
			virtual void mousePressEvent(const int& x ,const int& y , const int& button);
			virtual void mouseDoubleClickEvent(const int& x ,const int& y , const int& button);
			//virtual void mouseMoveEvent(const int& x ,const int& y, const int& button);
			virtual void clear();
		protected:
			void renderPoints();
			Ogre::Vector3 getPointCoordinate();
		private:
			VirtualMine::BaseRender::CMultiPoint* mpRenderPoints;
		};
	}
}

#endif  //_POINTMEASURETOOL_H
