//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : drillobject.h
//  @ Date : 2015/8/12
//  @ Author :王凯
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_FLAGOBJECT_H)
#define _FLAGOBJECT_H

#include "vrmine\vr_spatialobject\spatialobject_config.h"
#include "vrmine\vr_spatialinterface\igeoobject.h"
#include "vrmine\vr_style\style\pointstyle.h"
#include "vrmine\vr_geometry\geometry\point.h"
#include "vrmine\vr_spatialobject\geoproperty\cardmodelproperty.h"
#include <string>
using namespace std;

namespace VirtualMine
{
	namespace Mine
	{
		class VR_SPATIALOBJECT_DLL CFlagObject : public VirtualMine::SpatialInterface::CGeoObject
		{
		public: 
			CFlagObject(string type);
			~CFlagObject();
		public:
			VirtualMine::SpatialInterface::IStyle* getStyle();
			VirtualMine::SpatialInterface::IGeometry* getGeometry();
			VirtualMine::SpatialInterface::IGeoProperty* getGeoProperty();
			
		};
	}
}

#endif  //_FLAGOBJECT_H
