//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : rendertype.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_RENDERTYPE_H)
#define _RENDERTYPE_H


namespace VirtualMine
{
	namespace Mine
	{
		enum RenderType
		{
			RT_Raster,
			RT_Vector
		};
	}
}

#endif  //_RENDERTYPE_H
