//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : vectorobject.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_VECTOROBJECT_H)
#define _VECTOROBJECT_H

#include "..\base\igeoobject.h"


namespace VirtualMine
{
	namespace Mine
	{
		class VR_SPATIALOBJECT_DLL CVectorObject : public VirtualMine::Base::IGeoObject
		{
		};
	}
}

#endif  //_VECTOROBJECT_H
