//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : workingplaneproperty.h
//  @ Date : 2014/10/26
//  @ Author : 朱炜鹏
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(WORKINGPLANEPROPERTY_H)
#define WORKINGPLANEPROPERTY_H

#include "vrmine/vr_core/coredefine.h"
#include "vrmine/vr_spatialinterface/igeoproperty.h"
#include "vrmine\vr_spatialobject\spatialobject_config.h"


namespace VirtualMine
{
	namespace GeoProperty
	{
		class VR_SPATIALOBJECT_DLL CWorkingplaneProperty : public VirtualMine::SpatialInterface::CGeoProperty
		{
		public:
			CWorkingplaneProperty();
			~CWorkingplaneProperty();
		public:
			VirtualMine::SpatialInterface::IGeoProperty* clone();

			void setName(const std::string& name);
			std::string getName();
		private:
			std::string mName;
		};
	}
}

#endif  //WORKINGPLANEPROPERTY_H
