////
////
////  Generated by StarUML(tm) C++ Add-In
////
////  @ Project : 三维数字矿山平台
////  @ File Name : accessdataset.h
////  @ Date : 2014/7/6
////  @ Author : 盛佳良
////  @ Implement : 
////  @ Company : 中国矿业大学(北京)
////  @ Copyright:  2014-2020
////  @ Description : 
//
//
//#if !defined(_ACCESSDATASET_H)
//#define _ACCESSDATASET_H
//
//#include "idataset.h"
//
//namespace VR_DatabaseEngine
//{
//    namespace VirtualMine
//    {
//        namespace Database
//        {
//            class AccessDataset : public IDataSet
//            {
//            };
//        }
//    }
//}
//
//#endif  //_ACCESSDATASET_H
