////
////
////  Generated by StarUML(tm) C++ Add-In
////
////  @ Project : 三维数字矿山平台
////  @ File Name : accessdatasourceinfo.h
////  @ Date : 2014/7/6
////  @ Author : 盛佳良
////  @ Implement : 
////  @ Company : 中国矿业大学(北京)
////  @ Copyright:  2014-2020
////  @ Description : 
//
//
//#if !defined(_ACCESSDATASOURCEINFO_H)
//#define _ACCESSDATASOURCEINFO_H
//
//#include "idatasourceinfo.h"
//
//namespace VR_DatabaseEngine
//{
//    namespace VirtualMine
//    {
//        namespace Database
//        {
//            class AccessDataSourceInfo : public IDataSourceInfo
//            {
//            };
//        }
//    }
//}
//
//#endif  //_ACCESSDATASOURCEINFO_H
