//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : idatasourceinfo.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_IDATASOURCEINFO_H)
#define _IDATASOURCEINFO_H

#include "vrmine\vr_core\baseobject.h"
#include "vrmine\vr_databaseengine\database_config.h"
#include <string>

namespace VirtualMine
{
	namespace Database
	{
		class VR_DATABASEENGINE_DLL IDataSourceInfo// : public VirtualMine::Core::CBaseObject
		{
		public: 
			IDataSourceInfo();

			virtual void setDataSourceType(const std::string& type);

			virtual std::string getDataSourceType();

			virtual void setUri(const std::string& uri);

			virtual std::string getUri();
		};
	}
}

#endif  //_IDATASOURCEINFO_H
