////
////
////  Generated by StarUML(tm) C++ Add-In
////
////  @ Project : 三维数字矿山平台
////  @ File Name : ifield.h
////  @ Date : 2014/7/6
////  @ Author : 盛佳良
////  @ Implement : 
////  @ Company : 中国矿业大学(北京)
////  @ Copyright:  2014-2020
////  @ Description : 
//
//
//#if !defined(_IFIELDS_H)
//#define _IFIELDS_H
//
//#include "vrmine\vr_databaseengine\database_config.h"
//#include <string>
//#include "vrmine/vr_databaseengine/database/ifield.h"
//
//
//namespace VirtualMine
//{
//	namespace Database
//	{
//		class VR_DATABASEENGINE_DLL IFields
//		{
//		public:
//	    	virtual std::string getName();
//
//			virtual void setName(const std::string& name);
//	
//			virtual int getFieldCount();
//
//			virtual int findField(const std::string& fieldName);
//	
//			virtual int addField(IField* field);
//		
//			virtual void deleteField(const std::string& fieldName);
//		};
//	}
//}
//
//#endif  //_IFIELD_H
