//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : coallayerdataset.h
//  @ Date : 2014/8/6
//  @ Author : 王凯
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 

#if !defined(_MODELDATASET_H)
#define _MODELDATASET_H

#include "vrmine/vr_databaseengine/database/feature.h"
#include "vrmine/vr_databaseengine/database/dataset.h"
#include "vrmine\vr_databaseengine\database_config.h"
#include "vrmine/vr_databaseengine/database/coallayerfeature.h"

#include "vrmine/vr_core/geodatatype.h"

namespace VirtualMine
{
	namespace Database
	{
		class VR_DATABASEENGINE_DLL CModelDataset : public VirtualMine::Database::CDataset
		{
		public:

			CModelDataset();

			~CModelDataset(); 

			VirtualMine::Core::DeviceType getModelType();

			void setModelType(VirtualMine::Core::DeviceType type);

		private:
			VirtualMine::Core::DeviceType mModelType; ///


		/*	CCoalLayerFeature createFeature(const std::string& featureName);

			void destroyFeature(const std::string& featureName);

			CCoalLayerFeature* getFeature(int index);

			CCoalLayerFeature* getFeature(const std::string& featureName);
*/
		
/*		private:
			vector<CCoalLayerFeature*>* mpCoalLayerFeature;

	*/		

		};
	}
}

#endif //_MODELDATASET_H