//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : istyle.cpp
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#include "vrmine\vr_spatialinterface\istyle.h"

namespace VirtualMine
{
	namespace SpatialInterface
	{
		IStyle::IStyle()
		{
		
		}

		IStyle::~IStyle()
		{
		
		}

		CStyle::CStyle()
			:mColor(Ogre::ColourValue(1,1,0,1)),
			mHighlightColor(Ogre::ColourValue(1,0,0,1)),
			mType("")
		{
		
		}

		CStyle::~CStyle()
		{
		
		}
		
		Ogre::ColourValue& CStyle::getColor()
		{
			return this->mColor;
		}

		void CStyle::setColor(const Ogre::ColourValue& color)
		{
			this->mColor = color;
		}

		Ogre::ColourValue& CStyle::getHighlightColor()
		{
			return this->mHighlightColor;
		}
		void CStyle::setHighlightColor(const Ogre::ColourValue& color)
		{
			this->mHighlightColor = color;
		}

		IStyle* CStyle::clone()
		{
			throw std::exception();
		}

		std::string CStyle::getType()
		{
			throw std::exception();
		}

		std::string CStyle::toString()
		{
			return "";
		}
	}
}
