//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : fieldtype.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_VALUETYPE_H)
#define _VALUETYPE_H



namespace VirtualMine
{
	namespace Core
	{
		enum ValueType
		{
			VT_Int32,
			VT_Int16,
			VT_Float,
			VT_Double,
			VT_String,
			VT_Bool,
			VT_Char,
			VT_Blob,
			VT_Unkown,
			VT_UserDefine
		};
	}
}


#endif  //_FIELDTYPE_H
