//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : surfacerenderableobject.cpp
//  @ Date : 2021/11/29
//  @ Author :李佳康
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#include "vrmine\vr_spatialrender\spatialrender\lanewayrenderableprogress.h"
#include "vrmine/vr_arithmetic/arithmetic/geomeshcreatorregister.h"
//kk
#include "vrmine/vr_spatialrender/baserender/moveabletext.h"

using namespace VirtualMine::Arithmetic;
using namespace VirtualMine::SpatialInterface;

namespace VirtualMine
{
	namespace SpatialRender
	{
		CLanewayRenderableProgress::CLanewayRenderableProgress()
		{

		}

		CLanewayRenderableProgress::~CLanewayRenderableProgress()
		{

		}

		void CLanewayRenderableProgress::build(std::vector<Ogre::SceneNode*> &mTextNodes)
		{
			if (this->mGeoObjectVector.size()<=0) return;
			VirtualMine::SpatialInterface::GeoObjectVector::iterator ite =  this->mGeoObjectVector.begin();
			IGeoObject* firstGeoObject = (*ite);
			IGeoMeshCreator* meshCreator = VirtualMine::Arithmetic::CGeoMeshCreatorRegister::getSingletonPtr()->getGeoMeshCreator(firstGeoObject->getType());

			if (meshCreator == NULL)
			{
				return;
			}
			//kk传递mTextNodes
			CLanewayProgress_MeshCreator *meshCreatorPro = dynamic_cast<CLanewayProgress_MeshCreator*>(meshCreator);
			//meshCreator->createData(this->mGeoObjectVector,this->mDataVector,mTextNodes);
			meshCreatorPro->createData(this->mGeoObjectVector,this->mDataVector,mTextNodes);

			
			//this->mDataVector = *meshCreator->getGeoExtantionDataVector();
			this->mDataVector = *meshCreatorPro->getGeoExtantionDataVector();
		}

		void CLanewayRenderableProgress::render()
		{
			Ogre::SceneNode* sceneNode = dynamic_cast<Ogre::SceneNode*> (this->getNode());
			for (std::vector<CGeoExtentionData*>::iterator ite = this->mDataVector.begin();ite!=this->mDataVector.end();ite++)
			{
				CGeoExtentionData* geoExtentionData = (*ite);
				//kk,如果是text对象，需要设置他的位置
				//if (geoExtentionData->isTextObject)
				//{
				//	//this->ref_mpGeoSceneManager->getRootSceneNode()->createChildSceneNode(geoExtentionData->textPosition)->attachObject(dynamic_cast<VirtualMine::BaseRender::MovableText*>(geoExtentionData->getExtentionData()));
				//	//sceneNode->createChildSceneNode(geoExtentionData->textPosition)->attachObject(geoExtentionData->myMovableText);
				//}else{
				//	sceneNode->createChildSceneNode()->attachObject(geoExtentionData->getExtentionData());
				//}
				sceneNode->createChildSceneNode()->attachObject(geoExtentionData->getExtentionData());
				
			}
		}

		void CLanewayRenderableProgress::deRender()
		{

		}
	}
}
