//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : geomultirenderableobject.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_GEOMULTIRENDERABLEOBJECT_H)
#define _GEOMULTIRENDERABLEOBJECT_H

#include "vrmine\vr_spatialinterface\irenderableobject.h"
#include "vrmine\vr_spatialinterface\igeoobject.h"
#include "vrmine\vr_spatialrender\spatialrender_config.h"
#include <vector>

namespace VirtualMine
{
	namespace BaseRender
	{
		class VR_SPATIALRENDER_DLL CGeoMultiRenderableObject : public VirtualMine::SpatialInterface::IRenderableObject
		{
		public:
			CGeoMultiRenderableObject();
			virtual ~CGeoMultiRenderableObject();

			virtual void addGeoObject(VirtualMine::SpatialInterface::IGeoObject* pGeoObject);
			virtual void removeGeoObject(const int& index);
			virtual VirtualMine::SpatialInterface::IGeoObject* getGeoObject(const int& insdex); 
			VirtualMine::SpatialInterface::GeoObjectVector getGeoObjectVec();

			virtual int getGeoObjectCount();
			virtual void getGeoExtentionDatas(VirtualMine::SpatialInterface::GeoExtentionDataVector& geoExtensionDatas);
			virtual std::vector<VirtualMine::SpatialInterface::CGeoExtentionData*> getExtentionData();
			virtual void addGeoExtentionData(VirtualMine::SpatialInterface::CGeoExtentionData* data);
		 


		protected:
			VirtualMine::SpatialInterface::GeoObjectVector mGeoObjectVector;
			std::vector<VirtualMine::SpatialInterface::CGeoExtentionData*> mDataVector;
		};
	}
}

#endif  //_GEOMULTIRENDERABLEOBJECT_H
