//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : multipolygon.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_MULTIPOLYGON_H)
#define _MULTIPOLYGON_H

#include "geomultirenderableobject.h"


namespace VirtualMine
{
	namespace BaseRender
	{
		class VR_SPATIALRENDER_DLL CMultiPolygon : public CGeoMultiRenderableObject
		{
		};
	}
}

#endif  //_MULTIPOLYGON_H
