//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : multiline.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_MULTILINE_H)
#define _MULTILINE_H

#include "vrmine/vr_spatialrender/baserender/geomultirenderableobject.h"
#include "vrmine/vr_spatialobject/base/geoline.h"

namespace VirtualMine
{
	namespace BaseRender
	{
		class VR_SPATIALRENDER_DLL CMultiLine : public CGeoMultiRenderableObject
		{
		public:
			CMultiLine();
			virtual ~CMultiLine();
			virtual void build();
			virtual void render();
			virtual void dispose();
		protected:
			void convertGeoLineToRenderData(VirtualMine::Base::CGeoLine* pGeoLine);

		protected:
			Ogre::ManualObject* mpRenderableObject;
		};
	}
}

#endif  //_MULTILINE_H
