//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : line.cpp
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#include "vrmine/vr_maplayer/line2D.h"
#include "vrmine\vr_spatialinterface\iscene.h"

using namespace VirtualMine::SpatialInterface;

namespace VirtualMine
{
	namespace Map
	{

		CLine2D::CLine2D()
		{

		}

		CLine2D::~CLine2D()
		{

		}

		
		void CLine2D::addPointID( int ID )
		{
			this->mIDvector.push_back(ID);
		}

		int CLine2D::getPointID( const size_t& index )
		{
			assert(index < this->mIDvector.size());
			int p;
			p=this->mIDvector.at(index);
			return p;
		}

		void CLine2D::setLineName( std::string& name )
		{
			this->mName=name;
		}

		std::string CLine2D::getName()
		{
			return mName;
		}

		void CLine2D::setType( const int& type )
		{
			this->mType=type;
		}

		int CLine2D::getType()
		{
			return this->mType;

		}
	}
}

