//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 二三维爆破信息仿真系统
//  @ File Name : crectangle.cpp
//  @ Date : 2015/8/1
//  @ Author : 
//
//



#include "vrmine/vr_maplayer/rectangle.h"
namespace VirtualMine
{
	namespace Map
	{
		void CRectangle::setCenter() {

		}

		void CRectangle::getCenter() {

		}

		void CRectangle::setWidth() {

		}

		void CRectangle::getWidth() {

		}

		void CRectangle::setHeight() {

		}

		void CRectangle::getHeight() {

		}
	}}
