//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : geopolygon.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_GEOPOLYGON_H)
#define _GEOPOLYGON_H

#include "igeoobject.h"


namespace VirtualMine
{
	namespace Base
	{
		class VR_SPATIALOBJECT_DLL CGeoPolygon : public VirtualMine::Base::IGeoObject
		{

		};
	}
}

#endif  //_GEOPOLYGON_H
