//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : coalseamproperty.cpp
//  @ Date : 2014/8/6
//  @ Author : 朱炜鹏
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#include "vrmine/vr_spatialobject/geoproperty/coalseamproperty.h"

namespace VirtualMine
{
	namespace GeoProperty
	{
		CCoalSeamProperty::CCoalSeamProperty()
		{

		}
		CCoalSeamProperty::~CCoalSeamProperty()
		{

		}

		VirtualMine::SpatialInterface::IGeoProperty* CCoalSeamProperty::clone()
		{
			return NULL;
		}

		void CCoalSeamProperty::setName(const std::string& name)
		{
			this->mName = name;
		}

		std::string CCoalSeamProperty::getName()
		{
			return this->mName;
		}
	}
}
