//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : demobject.cpp
//  @ Date : 2014/8/6
//  @ Author : 朱炜鹏
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#include "vrmine/vr_spatialobject/mine/demobject.h"
#include "vrmine/vr_core/geodatatype.h"
#include "vrmine/vr_geometry/geometry/surface.h"
#include "vrmine/vr_databaseengine/database/demfeature.h"

using namespace VirtualMine::Database;

using namespace VirtualMine::SpatialInterface;
using namespace VirtualMine::Geometry;

namespace VirtualMine
{
	namespace Mine
	{
		CDemObject::CDemObject()
		{
			this->setType(VirtualMine::Core::GeoDataType::GDT_DEM);
		}

		CDemObject::~CDemObject()
		{

		}

		VirtualMine::SpatialInterface::IStyle* CDemObject::getStyle()
		{
			//VirtualMine::SpatialInterface::IStyle* pStyle =  CGeoObject::getStyle();
			//if (pStyle == NULL)
			//{
			//	pStyle = new VirtualMine::Style::CDrillHoleStyle();
			//	CGeoObject::setStyle(pStyle,true);
			//	//delete pStyle;
			//}
			return  CGeoObject::getStyle();
		}

		VirtualMine::SpatialInterface::IGeometry* CDemObject::getGeometry()
		{
			VirtualMine::SpatialInterface::IGeometry* pGeometry =  CGeoObject::getGeometry();
			if (pGeometry == NULL)
			{

				pGeometry = new  VirtualMine::Geometry::CGrid(100,100,30);
				
				//pGeometry = new  VirtualMine::Geometry::CGrid(191,315,30);
				//pGeometry = new  VirtualMine::Geometry::CGrid(193,285,30);
				//pGeometry = new  VirtualMine::Geometry::CGrid(285,193,30);
				
				CGeoObject::setGeometry(pGeometry,true);
				// delete pStyle;
			}
			return  CGeoObject::getGeometry();
		}

		VirtualMine::SpatialInterface::IGeoProperty* CDemObject::getGeoProperty()
		{
			//VirtualMine::SpatialInterface::IGeoProperty* pGeoProperty =  CGeoObject::getGeoProperty();
			//if (pGeoProperty == NULL)
			//{
			//	pGeoProperty = new VirtualMine::GeoProperty::CDrillProperty();
			//	CGeoObject::setGeoProperty(pGeoProperty,true);
			//	//delete pStyle;
			//}
			return  CGeoObject::getGeoProperty();
		}


		void CDemObject::fromFeature(VirtualMine::Database::IFeature* pFeature)
		{
			assert(pFeature);
			if (NULL == pFeature)
			{
				return;
			}
			void* pData = dynamic_cast<VirtualMine::Database::CDEMFeature*>(pFeature)->getPropertySet()->getFields().at(0).getVarient().data();
			int* id = (int*)pData;
			int getID = *id;

			void* pData1 = dynamic_cast<VirtualMine::Database::CDEMFeature*>(pFeature)->getPropertySet()->getFields().at(1).getVarient().data();
			char* name = (char*)pData1;

			void* pData2 = dynamic_cast<VirtualMine::Database::CDEMFeature*>(pFeature)->getPropertySet()->getFields().at(2).getVarient().data();
			Ogre::uchar* blob = static_cast<Ogre::uchar*>(pData2);
			int legth = dynamic_cast<VirtualMine::Database::CDEMFeature*>(pFeature)->getPropertySet()->getFields().at(2).getVarient().getLength();


			VirtualMine::Core::CVRDataStream ds;	
			ds.wirteBlob(blob,legth);
			ds.reseek(0);

			this->getGeometry()->fromStream(ds);

		}

		VirtualMine::Database::IFeature* CDemObject::toFeature()
		{



			VirtualMine::Core::CVRDataStream datastream;
			
			this->getGeometry()->toStream(datastream);
	
			VirtualMine::Database::IFeature* demfeature = new VirtualMine::Database::CDEMFeature();
			
			demfeature->setFieldBlob(datastream.getData(),datastream.getLength());
			demfeature->setFieldID(1);
			demfeature->setFieldName("DEM");


			return demfeature;

		}

	}

}
