//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : faultproperty.cpp
//  @ Date : 2014/8/6
//  @ Author : 朱炜鹏
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#include "vrmine/vr_spatialobject/geoproperty/faultproperty.h"

namespace VirtualMine
{
	namespace GeoProperty
	{
		CFaultProperty::CFaultProperty()
		{

		}

		CFaultProperty::~CFaultProperty()
		{

		}

		VirtualMine::SpatialInterface::IGeoProperty* CFaultProperty::clone()
		{
			return NULL;
		}

		void CFaultProperty::setName(const std::string& name)
		{
			this->mName = name;
		}

		std::string CFaultProperty::getName()
		{
			return this->mName;
		}

		void CFaultProperty::setDipAngle(const float& angle)
		{
			this->mDipAngle = angle;
		}

		float CFaultProperty::getDipAngle()
		{
			return this->mDipAngle;
		}

		void CFaultProperty::setHeight(const float& height)
		{
			this->mHeight = height;
		}

		float CFaultProperty::getHeight()
		{
			return this->mHeight;
		}
	}
}
