//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : igeoobject.cpp
//  @ Date : 2014/8/6
//  @ Author : 朱炜鹏
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#include "vrmine/vr_spatialobject/mine/flagobject.h"
#include "vrmine/vr_core/geodatatype.h"


#include "vrmine/vr_spatialinterface/iscene.h"


using namespace VirtualMine::Database;
using namespace VirtualMine::SpatialInterface;
using namespace VirtualMine::Core;

namespace VirtualMine
{
	namespace Mine
	{
		

		CFlagObject::CFlagObject(string type)
		{
			if (type == VirtualMine::Core::GeoDataType::GDT_ESCAPEROUTE)
			{
				this->setType(VirtualMine::Core::GeoDataType::GDT_ESCAPEROUTE);
			} 
			else if(type == VirtualMine::Core::GeoDataType::GDT_CONPROGRESS)
			{
				this->setType(VirtualMine::Core::GeoDataType::GDT_CONPROGRESS);
			}
		}

		CFlagObject::~CFlagObject()
		{

		}

		VirtualMine::SpatialInterface::IStyle* CFlagObject::getStyle()
		{
			VirtualMine::SpatialInterface::IStyle* pStyle =  CGeoObject::getStyle();
			if (pStyle == NULL)
			{
				pStyle = new VirtualMine::Style::CPointStyle();
				CGeoObject::setStyle(pStyle,true);
				//delete pStyle;
			}
			return  CGeoObject::getStyle();
		}

		VirtualMine::SpatialInterface::IGeometry* CFlagObject::getGeometry()
		{
			VirtualMine::SpatialInterface::IGeometry* pGeometry =  CGeoObject::getGeometry();
			if (pGeometry == NULL)
			{
				pGeometry = new  VirtualMine::Geometry::CPoint();
				CGeoObject::setGeometry(pGeometry,true);
				// delete pStyle;
			}
			return  CGeoObject::getGeometry();
		}

		VirtualMine::SpatialInterface::IGeoProperty* CFlagObject::getGeoProperty()
		{
			VirtualMine::SpatialInterface::IGeoProperty* pGeoProperty =  CGeoObject::getGeoProperty();
			if (pGeoProperty == NULL)
			{
			
				pGeoProperty = new VirtualMine::GeoProperty::CCardModelProperty();
				CGeoObject::setGeoProperty(pGeoProperty,true);
				//delete pStyle;
			}
			return  CGeoObject::getGeoProperty();
		}


	
	
	}

}
