//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : mineobject.cpp
//  @ Date : 2014/8/6
//  @ Author : 朱炜鹏
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#include "vrmine/vr_spatialobject/mine/mineobject.h"
#include "vrmine/vr_core/geodatatype.h"
#include "vrmine/vr_style/style/minestyle.h"
#include "vrmine/vr_geometry/geometry/mine.h"

#include "vrmine/vr_spatialobject/geoproperty/mineproperty.h"

using namespace VirtualMine::GeoProperty;
using namespace VirtualMine::Database;
using namespace VirtualMine::Style;
using namespace VirtualMine::SpatialInterface;
using namespace VirtualMine::Geometry;

namespace VirtualMine
{
	namespace Mine
	{
		CMineObject::CMineObject()
		{
			this->setType(VirtualMine::Core::GeoDataType::GDT_MINE);
		}

		CMineObject::~CMineObject()
		{

		}

		VirtualMine::SpatialInterface::IStyle* CMineObject::getStyle()
		{
			VirtualMine::SpatialInterface::IStyle* pStyle =  CGeoObject::getStyle();
			if (pStyle == NULL)
			{
				pStyle = new VirtualMine::Style::CMineStyle();
				CGeoObject::setStyle(pStyle,true);
				//delete pStyle;
			}
			return  CGeoObject::getStyle();
		}

		VirtualMine::SpatialInterface::IGeometry* CMineObject::getGeometry()
		{
			VirtualMine::SpatialInterface::IGeometry* pGeometry =  CGeoObject::getGeometry();
			if (pGeometry == NULL)
			{
				pGeometry = new  VirtualMine::Geometry::CMineGeometry();
				CGeoObject::setGeometry(pGeometry,true);
				// delete pStyle;
			}
			return  CGeoObject::getGeometry();
		}

		VirtualMine::SpatialInterface::IGeoProperty* CMineObject::getGeoProperty()
		{
			VirtualMine::SpatialInterface::IGeoProperty* pGeoProperty =  CGeoObject::getGeoProperty();
			if (pGeoProperty == NULL)
			{
				pGeoProperty = new VirtualMine::GeoProperty::CMineProperty();
				CGeoObject::setGeoProperty(pGeoProperty,true);
				//delete pStyle;
			}
			return  CGeoObject::getGeoProperty();
		}

		void CMineObject::fromFeature(VirtualMine::Database::IFeature* pFeature)
		{
								
		}

		VirtualMine::Database::IFeature* CMineObject::toFeature()
		{
			return NULL;
		}

	}

}
