//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : modelproperty.cpp
//  @ Date : 2014/8/6
//  @ Author : 朱炜鹏
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#include "vrmine/vr_spatialobject/geoproperty/modelProperty.h"

namespace VirtualMine
{
	namespace GeoProperty
	{
		CModelProperty::CModelProperty()
		{
			this->mMeshName = "";
			this->setDeviceType();
		}

		CModelProperty::~CModelProperty()
		{

		}

		VirtualMine::SpatialInterface::IGeoProperty* CModelProperty::clone()
		{
			return NULL;
		}

		void CModelProperty::setDeviceType(VirtualMine::Core::DeviceType devicetype /* = VirtualMine::Core::DeviceType::DT_UNKNOWN */)
		{
			this->mDeviceType = devicetype;
		}
		VirtualMine::Core::DeviceType CModelProperty::getDeviceType()
		{
			return this->mDeviceType;
		}

		void CModelProperty::setMeshName(const std::string& meshName)
		{
			this->mMeshName = meshName;
		}

		std::string CModelProperty::getMeshName()
		{
			return this->mMeshName;
		}

		void CModelProperty::toStream(VirtualMine::Core::CVRDataStream& datastream)
		{
		    datastream.wirteString(mMeshName);
		}

		void CModelProperty::fromStream(VirtualMine::Core::CVRDataStream& datastream)
		{
			datastream.readString(mMeshName);			
		}



	}
}
