//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : coordinatetype.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_COORDINATETYPE_H)
#define _COORDINATETYPE_H


namespace VirtualMine
{
	namespace CoordinateSystem
	{
		enum CoordinateType
		{
			CT_Proj,
			CT_Geo
		};
	}
}

#endif  //_COORDINATETYPE_H
