
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : coordinatecalculator.h
//  @ Date : 2015/7/6
//  @ Author : 王向上
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_COORDINATECALCULATOR_H)
#define _COORDINATECALCULATOR_H

#include "coordinatesystem_config.h"
#include"vrmine/vr_core/coredefine.h"
#include "gdal_include/proj_api.h"
#include<cmath>
#include "ogre/Ogre.h"
using namespace std;

namespace VirtualMine
{
	namespace CoordinateSystem
	{
		class VR_COORDINATESYSTEM_DLL CoordinateCalculator
		{
		public:
			void transformCoordinate();
		public:
			Ogre::Vector3 Xian80toWGS84(Ogre::Vector3& in_point,sevenPara& inPara);
			Ogre::Vector3 WGS84toXian80(Ogre::Vector3& in_point,sevenPara& inPara);
			Ogre::Vector3 BJ54toWGS84  (Ogre::Vector3& in_point,sevenPara& inPara);
			Ogre::Vector3 WGS84toBJ54  (Ogre::Vector3& in_point,sevenPara& inPara);
			Ogre::Vector3 BJ54toXian80 (Ogre::Vector3& in_point,sevenPara& inPara);
			Ogre::Vector3 Xian80toBJ54 (Ogre::Vector3& in_point,sevenPara& inPara);

			std::string  int2str(int n);

			//projUV Xian80_GridtoLL(KGrid& grid,int band);

			projUV  Xian80_LLtoGrid(double lon,double lat,int band);

			projUV WGS84_GridtoLL(double lon,double lat,int band);

			//projUV WGS84_LLtoGrid(Latlon& latlon,int band);
		};
	}
}

#endif  //_COORDINATECALCULATOR_H
