//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : spatialreference_beijing54.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_SPATIALREFERENCE_BEIJING54_H)
#define _SPATIALREFERENCE_BEIJING54_H

#include "vrmine\vr_spatialinterface\ispatialreference.h"
#include "vrmine\vr_coordinatesystem\coordinatesystem\coordinatesystem_config.h"

namespace VirtualMine
{
	namespace CoordinateSystem
	{
		class VR_COORDINATESYSTEM_DLL CSpatialReference_BeiJing54 : public VirtualMine::SpatialInterface::CGaussPrjBase
		{
		public:
			CSpatialReference_BeiJing54();
			virtual ~CSpatialReference_BeiJing54();
		};
	}
}

#endif  //_SPATIALREFERENCE_BEIJING54_H
