//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : spatialreferencetype.h
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#if !defined(_SPATIALREFERENCETYPE_H)
#define _SPATIALREFERENCETYPE_H


namespace VirtualMine
{
	namespace CoordinateSystem
	{
		enum SpatialReferenceType
		{
			SRT_BeiJing54,
			SRT_XiAn80,
			SRT_WGS84
		};
	}
}

#endif  //_SPATIALREFERENCETYPE_H
