//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维数字矿山平台
//  @ File Name : idataset.cpp
//  @ Date : 2014/7/6
//  @ Author : 盛佳良
//  @ Implement : 
//  @ Company : 中国矿业大学(北京)
//  @ Copyright:  2014-2020
//  @ Description : 


#include "vrmine\vr_databaseengine\database\idataset.h"

using namespace std;
using namespace VirtualMine::Database;

IDataset::IDataset()
{

}

//IFeature IDataset::createFeature(const string& featureName)
//{
//	IFeature* feature = new IFeature();
//	//feature->setName(featureName);
//	return *feature; 
//}

void  IDataset::addFeature(IFeature feature)
{

}

void IDataset::destroyFeature(IFeature feature)
{

}

IFeature* IDataset::getFeature(const int& index)
{
	return NULL;
}

IFeature* IDataset::getFeatureByID(const int& id)
{
	return NULL;
}

 IFeature* IDataset::getFeature(const std::string& name)
{
	return NULL;
}

void IDataset::setName(const std::string& name) 
{

}

string IDataset::getName()
{
	return "";
}

string IDataset::getType()
{
	return "";
}

void IDataset::setType(const std::string& type)
{

}


int IDataset::getCount()
{
	 return -1;
}

std::vector<IFeature*>* IDataset::getFeatureList()
{
	return NULL;
}